### PR TITLE
feat: add to calendar feature

### PR DESCRIPTION
**Pull request by LudeeD**
Hey, I think this would be a nice feature for users to quickly add sessions to their calendars. At least I would like it.

Here its my attempt at it. Feel free to comment, or reject!

It kind of looks like this on my development setup, it uses a lib to create the ics file that is then downloaded

image

### CODE REVIEW

**Comment by Kajatin** [comment]
Hey @LudeeD!

Thank you for taking an interest in this project. I love your idea and it is something that I'd be happy to merge.

There are a few changes I'd ask you to make before I can merge the PR:

1. The button to download the `.ics` file should be its own client component (i.e. not implemented inside the `LocalTime` component. You can pass in the `session` object directly as a prop and compute values inside this component.
2. This download component should only be shown to people who are signed up to the session.
3. This component doesn't fit horizontally next to the date. I'd suggest to either just make the date text clickable and you'd get the `.ics` file directly from there, or if you want to make an explicit button for it, please add it besides the other buttons (e.g. Cancel, on the right side of the event). If you pick the latter option, the text would be too long for this button, so I'd suggest using only an icon for the button's body. There are some suggestions here: https://fonts.google.com/icons?icon.query=calendar and Material Icons are already integrated in the project. You can add them simply by: `<div className="material-symbols-outlined">calendar_month</div>`.

Please also make sure to run `npm run build` when you're done with your changes. 😊

**Comment by LudeeD** [comment]
I removed the button and added the action as a onclick on the div
npm run build is still failing but I think its because its trying to connect to a database to build server side pages :/

**Comment by Kajatin** [comment]
Thanks, I love it 😁 

It does build, but when I ran it locally, it didn't work. I get these error from the `createEvent()` function (and I don't get any ics download either). Do you have any idea what might be wrong here?

Screenshot 2023-10-22 at 21 17 28

**Comment by LudeeD** [comment]
nice catch, should be fixed now

**Comment by Kajatin** [comment]
I'm sorry to throw it back again, but the start and end times are the same in the downloaded `ics` file :/ Any chance you could fix that?

**Review by Kajatin — APPROVED** [review]

**Pull request merged**
